CREATE TABLE ai_request_log (
    id BIGSERIAL PRIMARY KEY,
    client_request_id VARCHAR(100) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    source VARCHAR(20) NOT NULL,
    mode VARCHAR(50) NOT NULL,
    language VARCHAR(20) NOT NULL,
    status VARCHAR(50) NOT NULL,
    plan_type VARCHAR(50) NOT NULL,
    model_used VARCHAR(255),
    answer VARCHAR(4000),
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    estimated_request_cost_eur DOUBLE PRECISION NOT NULL,
    request_allowed BOOLEAN NOT NULL,
    remaining_requests INTEGER NOT NULL,
    monthly_usage_percent INTEGER NOT NULL,
    estimated_monthly_cost_eur DOUBLE PRECISION NOT NULL,
    monthly_cost_cap_eur DOUBLE PRECISION NOT NULL,
    throttle_state VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_ai_request_log_user_client_request_id UNIQUE (user_id, client_request_id)
);
